### ISSUE TITLE
Just Share

### ISSUE THREAD

**Issue by aminantoo** [opencartbrasil/instalador-sem-ftp#1]
Well, this small VQMod file is very usefull. But there is an error when  I was using this file in OC. 2.0.0.0. so, I modified that a little. I've changed the xml file. 
The position attribute now in search tag. I did it for both of the operation tag.
and I've changed this line:
$directory = DIR_UPLOAD . str_replace(array('../', '..\', '..'), '', $this->request->post['path']) . '/upload/';
to:
$directory = DIR_DOWNLOAD . str_replace(array('../', '..\', '..'), '', $this->request->post['path']) . '/upload/';
it works properly in my sistem now.

thanks

**Comment by v5mvidal** [comment]
This error occurs in version 2.0.0.0 for in it there is no DIR_UPLOAD in version 2.0.1.1 hesitate the DIR_UPLOAD and the error does not occur.

Thank you for the information. :)
