### ISSUE TITLE
FTP needs to be enabled

### ISSUE THREAD

**Issue by AngelinDark** [opencartbrasil/instalador-sem-ftp#2]
Olá. Obrigado pela modificação.

Por algum motivo mesmo tendo instalado a modificação ainda recebo a mensagem "FTP needs to be enabled in the settings" ao tentar fazer o upload de uma extensão pelo Extension Installer.

Segui os passos conforme descrito, mas não parece estar funcionando. Alguém consegue imaginar o que pode estar acontecendo de errado?

**Comment by AngelinDark** [comment]
Tinha esquecido de dar refresh, falha minha. Desculpe.

**Comment by v5mvidal** [comment]
Que bom que conseguiu. :)
