### ISSUE TITLE
Não consegui instalar usando este instalador

### ISSUE THREAD

**Issue by giovannipds** [opencartbrasil/instalador-sem-ftp#3]
Oi @ManoelVidal, tudo bem?

Eu Instalei uma versão local do OpenCart na minha máquina, mas quando fui instalar essa tradução, seguindo as orientações recomendadas por vocês na OpenCart Brasil e aqui, como não tenho FTP, ao fazer upload do arquivo desse repositório, ele é feito com sucesso, atualizo a loja na página Modifications mas nada muda, exceto a home da loja, onde aparece uma página de manutenção (em inglês). A versão do OpenCart é a 2.0.3.1.

Sabe me dizer o que pode estar acontecendo?

Abraços. Att. Gio

**Comment by v5mvidal** [comment]
Olá,

O que não conseguiu instalar, está modificação ou a tradução?

**Comment by giovannipds** [comment]
Oi @ManoelVidal.

Não consegui instalar a tradução usando esta modificação. A modificação, se não me engano, instalou normalmente, mas o envio da tradução não alterava nada.

Já instalando a tradução através de um FTP funcionou tranquilamente, daí o que eu acabei fazendo foi instalar num FTP e baixar os arquivos pro local.

Att. Gio

**Comment by v5mvidal** [comment]
Que bom que resolveu.

**Comment by giovannipds** [comment]
Sim, resolvi, mas de uma forma diferente do ideal. Legal seria entendermos o problema e tentarmos resolvê-lo pros próximos que possam tentar usá-lo de forma local... não acha? Tentes fazer uma instalação local e usar a tradução seguindo essas instruções. Abraços.

**Comment by v5mvidal** [comment]
Faço sempre o teste localmente e depois testo online e sempre funciona. Escrevi o manual de instalação exatamente como faço. Minha plataforma local para teste é Windows + Apache + PHP + MySQL; e online é CentOS 6 + Apache x Nginx + PHP + MySQL. :+1:

**Comment by giovannipds** [comment]
Certo... ok, minha plataforma local é a mesma, e quando fui seguir os passos, não funcionou.

Numa próxima instalação vou testar novamente, se precisar, até gravar, pra lhe mostrar o que ocorre.

Se tiver alguém que conhece que pode testar, pra ver se o mesmo também não irá conseguir, marque-o aqui.

Abraços.

**Comment by v5mvidal** [comment]
Vou fechar, caso haja alguma novidade abriremos novamente.

**Comment by giovannipds** [comment]
:+1:
