### ISSUE TITLE
Permission Denied while creating files. 

### ISSUE THREAD

**Issue by leopucci-zz** [opencartbrasil/instalador-sem-ftp#4]
Getting Permission denied on 
/system/modification/admin/controller/extension/installer.php while creating files. 
My system is using apache user with 755, but not being able to create folders and files

**Comment by leopucci-zz** [comment]
chmod -R 777 *

This solved, 

Just remember to after that fix permissions to default:
chmod -R 755 *

**Comment by v5mvidal** [comment]
Thanks for the tip.
