### ISSUE TITLE
Instalador sem FTP parece não fazer efeito

### ISSUE THREAD

**Issue by alexandreaugusto** [opencartbrasil/instalador-sem-ftp#5]
Olá, após fazer a habilitação do instalador sem FTP, fui tentar instalar a tradução do OpenCart 2.3.0.2, oferecida também por vocês. Porém, obtenho o seguinte erro:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

OK

<b>Warning</b>: mkdir(): Permission denied in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): Permission denied in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/pt-br.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/pt-br.png): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/catalog//language/pt-br/pt-br.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/catalog//language/pt-br/pt-br.png): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: mkdir(): No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>491</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/catalog/attribute.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/catalog/attribute_group.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/catalog/category.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/catalog/download.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/catalog/filter.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/catalog/information.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/catalog/manufacturer.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/catalog/option.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/catalog/product.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/catalog/recurring.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/catalog/review.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/common/column_left.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/common/dashboard.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/admin/controller/extension/installer.php</b> on line <b>498</b><b>Warning</b>: copy(/home/alexandre/workspace/opencart/admin//language/pt-br/common/filemanager.php): failed to open stream: No such file or directory in <b>/home/alexandre/workspace/opencart/system/storage/modification/ad

**Comment by v5mvidal** [comment]
A mensagem de erro informa que os diretórios do OpenCart não tem permissão de escrita, ou seja, não tem nada haver com o instalador sem ftp, mas sim com as permissões dos diretórios.

**Comment by alexandreaugusto** [comment]
Obrigado pela ajuda Manoel! Funcionou após eu mudar o dono de todos os diretórios para o usuário que executa o servidor web. Só fiquei na dúvida de qual diretório deveria ter permissão, sendo que eu já havia conseguido instalar o OpenCart com sucesso, seguindo as regras das permissões de diretório necessárias!
