### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by Devfishingman** [opencartbrasil/instalador-sem-ftp#6]
Olá, não consigo instalar essa extensão na minha versão 2.3 do opencart. Simplesmente ocorre o erro "internal server error" no meio do upload do xml. O que posso fazer?

**Comment by v5mvidal** [comment]
Olá @Devfishingman 

Essa mensagem é genérica, ou seja, ela pode significar muitos problemas em sua hospedagem, por isso fico difícil de ajudar.

Tire um printscreen da tela com o erro e poste aqui.

**Comment by Devfishingman** [comment]
@v5manoel , Estou usando uma hospedagem linux (ubuntu 14.04) na digital ocean. Estranhei esse erro genérico, todas as extensões do php e afins estão instaladas corretamente! 

Eu gostaria MUITO de utilizar o opencart3 neste projeto, mas, estou refém de um template que só funciona na versão 2 :(

**Comment by v5mvidal** [comment]
@Devfishingman, a mensagem "internal server error" é referente ao erro 500, que na maioria dos casos indica que há algum problema no servidor.

Geralmente esse erro ocorre no instalador pelos seguintes motivos:

- Falta permissões nas pasta do OpenCart (644 para arquivos e 755 para pastas).
- O usuário do apache ou nginx não tem permissão de escrita para as pastas do OpenCart.
- A biblioteca ZIP do PHP não foi instalada.

Verifique se realmente está tudo funcionando.
